blank_issues_enabled: true
contact_links:
  - name: Diskusi Tim
    url: https://github.com/moriuz123/projek-portal/discussions
    about: Gunakan ini untuk diskusi ide, keputusan teknis, atau pertanyaan umum.
